### ISSUE TITLE
Definition for the extensions term causes problems with JSON-LD operations

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#425]
The current definition for the `extensions` term in our contexts causes problems with JSON-LD operations.

Currently, we treat the _value_ of an extensions property as a _Node Object_:
```
"extensions": {"@id": "caliper:extensions", "@type": "@id"}
```

From the [JSON-LD spec, section 9.2](https://w3c.github.io/json-ld-syntax/#node-objects):
> A node object MUST be a dictionary. All keys which are not IRIs, compact IRIs, terms valid in the active context, or one of the following keywords (or aliases of such a keyword) MUST be ignored when processed.

What this means is that if you perform a JSON-LD operation on Caliper event or entity with an `extensions` property, the contents of that extensions property will get dropped during the operation.

However, if we treat the value of an extensions property as an _Index Map_ instead, then it's contained values should get _preserved_ during JSON-LD operations:
```
"extensions": {"@id": "caliper:extensions", "@container": "@index"}
```

Again, from the [JSON-LD spec, section 9.9](https://w3c.github.io/json-ld-syntax/#index-maps):
> An index map allows keys that have no semantic meaning, but should be preserved regardless, to be used in JSON-LD documents.

Furthermore [section 4.6.1](https://w3c.github.io/json-ld-syntax/#data-indexing) seems to reinforce the value of this use.

Note that the members of an index map MUST be one of the types listed in section 9.9 of the JSON-LD spec, but basically boil down to a fundamental terminal value type (like "string", "number", "null", "true", "false"), or a more complicated value (node object, value object, list object, set object, or array of one of the other allowed types).

I believe this will satisfy our best practice that recommends that `extensions` be treated like a simple-key value store. It's not clear if this will satisfy more complicated uses of `extensions` (like putting node objects referring non-Caliper context documents into the map)...

**Comment by ViktorHaag** [comment]
It's pretty clear that if `extensions` contains a value that itself is an object, the JSON-LD processing will treat that as a node, and ignore it's contents... for reference see the `caliperEventViewViewedExtended.json` fixture; the top-level extensions property in the fixture has this value:
```
'extensions': {
  'job': {
    'id': '08c1233d-9ba3-40ac-952f-004c47a50ff7',
    'jobDate': '2016-11-16T01:01:00.000Z',
    'jobTag': 'caliper_batch_job'
  }
}
```
setting extensions to be an index map produces this when you first expand and then compact the fixture using the standard Caliper context:
```
 'extensions': {
   'job': {
      'id': '08c1233d-9ba3-40ac-952f-004c47a50ff7'
  }
},
```

The `id` property gets preserved because that actually maps to a known Caliper term. But the other terms, which Caliper doesn't know about, get lost. This seems sub-optimal. 8(

**Comment by ViktorHaag** [comment]
The latest draft|editors version of the JSON-LD spec [lists an `@json` type for term definitions with JSON literal values](https://w3c.github.io/json-ld-syntax/#json-literals) which seems promising to address this issue as well, but it's explicitly called out as non-normative, and thus I suspect has little to no adoption in existing JSON-LD tooling.

**Comment by ViktorHaag** [comment]
As it stands, it seems like we have two simple routes:
- Any treatment of Caliper events or entities as JSON-LD entities will have to ignore the `extensions` field, unless there's a context that defines the terms in it in a JSON-LD way.
- We insist that by best practice `extensions` only contain a flat key-value map with string key names and JSON terminal types as values, and that more complex use of it "may cause problems" (meaning that Sensors can't just jam a JSON literal object in there and hope that the receiver will actually retain it).

Either way, certification on this point seems like it could be challenging. We may want to say that the `extensions` property on any Event or Entity is explicitly _ignored_ for the purposes of certification... 8(

**Comment by joshuamcghee** [comment]
@ViktorHaag does this require any updates to the 1.2 main spec doc?

**Comment by ViktorHaag** [comment]
I'm not confident in an approach that gets past this fundamental JSON-LD problem. Anthony might have good ideas about this, but the point may be moot anyway, depending on what happens to Caliper post 1.2 (seems like doing away with JSON-LD entirely in some new vision of Caliper might be in play).

I think we recognize this as an ongoing concern, don't make any kind of adjustment to 1.2 for it, and perhaps note that we explicitly ignore the contents of any `extensions` field on an event or entity during certification.

**Comment by ViktorHaag** [comment]
@joshuamcghee and @bracken  -- I'm turning a corner a bit on this one; I think we should:
- explicitly ignore the `extensions` property wherever it occurs in Events and Entities, for the purposes of certification
- explicitly say this in the certification guide, and perhaps also the specification

In the light of it's problematic status with respect to JSON-LD, I think we have to take some explicit stance on it for Caliper v1.2, and the best stance in my opinion is to simply state that we're taking it out of bounds.

Implementations that do want to use it can fill their boots, but they should also realize that unless used quite carefully, it can likely bork their ability to properly handle it during JSON-LD operations. (I'm not sure we need to say much around _that_ because I think implementations depending on Caliper to be "proper JSON-LD" probably need to generally know what they're doing anyway.)

**Comment by bracken** [comment]
@ViktorHaag I think that's a good approach.

I just looked in the implementation guide to see where to add that, and noticed there isn't even a section explicitly on using the  `extensions` field, so we should probably add that section where it makes sense and make sure to include your note from this.
