### ISSUE TITLE
generated property values for QuestionnaireItemEvent

### ISSUE THREAD

**Issue by ssciolla** [1EdTech/caliper-spec#426]
Per a conversation with @arwhyte , `QuestionnaireItemEvent` and `AssessmentItemEvent` should specify that the value of the `generated` property should be an `Attempt` entity when the action is `Started` or `Skipped`. This needs to be corrected in the `QuestionnaireItemEvent` and `AssessmentItemEvent` sections and `Survey Profile` sections of the specification. The mentions of `AssessmentItemEvent` in the `Assessment Profile` section appear to be correct.

**Comment by joshuamcghee** [comment]
@ssciolla Not sure where it was done but it looks like this was resolved.
