### ISSUE TITLE
Terminology definitions are confusing respec processor

### ISSUE THREAD

**Issue by amiller-ims** [1EdTech/caliper-spec#455]
The term definitions in caliper-spec-v1p2.html use the `name` attribute:
```
<a name="actorDef"></a>
```
This confuses the latest version of w3c\respec and it can't resolve links to `#actorDef`.

We'd prefer it if you could change the them to use the `id` attribute like this:
```
<a id="actorDef"></a>
```
But if that is too hard, we could add a workaround to the IMS version of Respec.

**Comment by arwhyte** [comment]
Switched to `<section id="actorDef" class="notoc">`.  Updated all instances of `<a name="[someIdentifier">` except in the case of ye olde `caliper-spec.md` doc.  We plan to delete that doc from the develop branch when work on the updated spec is complete.
