### ISSUE TITLE
LikertScale Entity typo `points` -> `scalePoints` 

### ISSUE THREAD

**Issue by andrew-gardener** [1EdTech/caliper-spec#464]
https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/entities/caliper-entity-likertscale.html#L38

https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/entities/caliper-entity-likertscale.html#L13

**Comment by bracken** [comment]
Thanks Andrew!
