### ISSUE TITLE
Images not loading properly in Caliper v1.2 spec doc

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#470]
All the images in the spec at https://www.imsglobal.org/spec/caliper/v1p2 are broken.

**Comment by bracken** [comment]
Woops, that's my fault. I must have forgotten to update the paths the last time I updated it.

**Comment by joshuamcghee** [comment]
@bracken just confirmed this is still broken as of 2/25/2020

**Comment by bracken** [comment]
@joshuamcghee, yeah, I thought I knew how to fix them but I was wrong. Matt showed me how and I'll do it next time I update them. I wanted to get the couple outstanding PRs merged before I did that again.

**Comment by bracken** [comment]
Latest published versions now have correct image URLs.
