### ISSUE TITLE
5.1 Behaviour

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#481]
> create in-memory object representations of Caliper Event and Entity types as described in Section 2.0. The particular Event and Entity types that a Sensor must be capable of expressing are determined by the profiles implemented as described in Section 3.0.

This is a ridiculous requirement. There's no need at all to require a Sensor to "create in-memory object representations of Caliper Event and Entity types", in fact, it almost certainly won't be the pattern that implementations actually use.

It's far more likely that they will:
- have their own "in memory representations" that are simply able to serialize themselves as valid Caliper, or
- have a translation library that's generally used on an activity stream, well after the event-generating components have generated events, to take natively expressed activity statements and translate them into valid Caliper

The only thing that's required is that an application that wants to certify as valid Caliper be capable of sending activity statements expressed in valid Caliper JSON to a receiving endpoint.

This entire section needs to be re-written to remove this implementation burden on sensors having native, "in-memory" representations of Caliper objects. The only bullet that seems relevant to me at all, really, is the very last one.

**Comment by joshuamcghee** [comment]
@ViktorHaag Rolled changes for this into #488.  Let me know if this works for you.
