### ISSUE TITLE
5.4 HTTP Requests "MUST be sent using POST", not for configuration GETs

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#484]
This passage doesn't admit for GET on the endpoint for configuration requests. The wording in 5.4 must make it clear that:
- GET only for retrieving endpoint config
- POST only for sending event/entity data to the endpoint

**Comment by bracken** [comment]
I think section 5 as a whole is about sending events so only talking about the POST stuff is fine. Section 6 gets into the Caliper endpoint/server and 6.2 covers the GET in relation to the configuration stuff. I don't think section 5.4 really needs to reference that.

**Comment by ViktorHaag** [comment]
> I think section 5 as a whole is about sending events so only talking about the POST stuff is fine. Section 6 gets into the Caliper endpoint/server and 6.2 covers the GET in relation to the configuration stuff. I don't think section 5.4 really needs to reference that.

We need to remember that people read in an order and definitive statements may take hold more securely than the exceptions. We should properly setup the expectations about the difference in behaviour rather than say it like "<This> is always true... blahblahblah... Except in <this> case", I think.
