### ISSUE TITLE
6.3 String Lengths and STorage has broken cross reference to an Appendix G

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#485]
> See Appendix G. Minimum Supported String Lengths for a list of Caliper data properties and recommended minimum string lengths.

This cross reference is broken, and Appendix G seems to cover other material.

We should just remove this sentence, or replace it with actual content in section 6.3 and not yet-another-appendix.

**Comment by joshuamcghee** [comment]
We noticed this whole appendix is missing, Bracken and I will do a review and update.
