### ISSUE TITLE
2.1 Event and 2.2 Entity should have forward references to their concordances

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#486]
Each of these sections should have a reference that says something like "for a complete list of Events, see Appendix xxx" to forward reference.

Each of the _appendices_ for these should have a back reference in a blurb at the top of each appendix section that says something like "A Caliper Entity is a generic type that represents objects that participate in learning-related activities. For a description of the properties common to all Entities, see section xxx" to backward reference.

**Comment by joshuamcghee** [comment]
added the hops in per your recommendation
