### ISSUE TITLE
B.27 LearningObjective needs an example/fixture

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#489]
This has no example (and thus no fixture?) currently; it needs one.

**Comment by ViktorHaag** [comment]
See also PR https://github.com/IMSGlobal/caliper-spec/pull/491 and issue #491

**Comment by bracken** [comment]
That PR was merged, does that mean this can be closed? It looks like it.

**Comment by joshuamcghee** [comment]
@ViktorHaag closing this, please feel free to re-open if you feel it's not resolved
