### ISSUE TITLE
F. LIS Roles: sub roles should also specify the principal role need explanation

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#493]
This phrase seems an odd thing to assert:
> Whenever a sub-role is specified, the related context role SHOULD also be included. For example, a role of Instructor#TeachingAssistant SHOULD always be accompanied by the Instructor role.

So, I propose that we either say "As in the LTI specification", or we should back this sentence up with "For clarity to the receiver,..." and with an example of what's meant by this sentence.

**Comment by joshuamcghee** [comment]
Adding this to the agenda for Tuesday's call
