### ISSUE TITLE
H. LTI Message Types is missing the deep linking response message type

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#494]
We're missing the `LtiDeepLinkingResponse` message type.

When `ToolLaunchEvent.action` is _Returned_, then `ToolLaunchEvent.target` can be an LTI Link that is the end point on the platform the flow is returning _back to_. In these cases, the `LtiLink.messageType` property on this link would be expected to be a _response_ message (and currently we only recognize `LtiDeepLinkingResponse` as a response message).

**Comment by bracken** [comment]
Resolved in https://github.com/IMSGlobal/caliper-spec/pull/488
