### ISSUE TITLE
M. List of Contributors -- why include country? role?

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#496]
It seems odd to include country of organization next to organization, especially as many organizations will have contributors in several countries (in which case, "where" is D2L located? Where the contributing employee resides? Where the corporate HQ is?)

Also, I see no need at all for the role column -- all contributors contributed; I see no need to discriminate based on what notional "kind" of contribution they made.

**Comment by joshuamcghee** [comment]
I'm not sure the history behind why this was done this way.  I'll add this to the agenda for discussion 2/4/2020

**Comment by joshuamcghee** [comment]
@joshuamcghee Will remove reference to role and country and add additional members.
