### ISSUE TITLE
Impl 12 and 13 (and cert guide 5, 6, 7) -- back matter should be consistent

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#497]
We should be consistent about where we put the back matter. The list of contributors and change history for the Implementation Guide should use the same template as used in the specification.

Same comment applies to the cert guide -- the back matter should be in the same locations as used in the spec.

**Comment by joshuamcghee** [comment]
We will move these into appendices for consistency across the doc set
