### ISSUE TITLE
IRI --> IRN and IRL, not IRI --> URN and URL

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#502]
We might want to tighten our term use around this in all our documents. If we're going to use IRI (and we have particular technical reasons for wanting to), then we should use the terms IRN and IRL because _they are not equivalent to URN and URL_ (i.e. the allowable character set is not at all the same).

**Comment by joshuamcghee** [comment]
@bracken @joshuamcghee to do a review of the use of these terms in the docs.

**Comment by bracken** [comment]
Thanks for the PR work Viktor!
