### ISSUE TITLE
Impl. -- 5. Metric Profiles --> present the formal vocabulary for identifying profiles

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#503]
This section ought to make it clear that the _profiles_ themselves are identified by vocabulary terms, and why and how those are used.

**Comment by bracken** [comment]
Do you mean like explaining that an Event's `profile` property can be used and is limited by the vocabulary list for profiles?

**Comment by bracken** [comment]
New subsection:
explain the field, and that an event can be interpreted differently depending on the profile its in.

**Comment by ViktorHaag** [comment]
^ Also that we really want people to use Event.profile (strongly recommended? SHOULD?) -- it's only owing to backwards compatibility that we're not making it mandatory.

**Comment by bracken** [comment]
@ViktorHaag is the vocabulary for the profiles anywhere other than the context file? I can't find anything about it in the main spec to reference from the implementation guide.

**Comment by ViktorHaag** [comment]
@bracken -- Currently, I don't believe it's anywhere but the context file, and the python reference implementation code.

**Comment by bracken** [comment]
@ViktorHaag, Is this something that should be in an appendix or something in the main spec doc do you think? I don't know enough about how people would know to use the context file to know if that's sufficient.

**Comment by ViktorHaag** [comment]
This definitely needs to be in the main spec -- the short terms of the profile names as vocabulary (not necessarily the full URIs, I think?) and docs for `Event.profile`; I expect we'd treat documenting the vocabulary terms in that list the same way we do the other vocab terms we have (status, roles, system id types, etc).

**Comment by bracken** [comment]
Great, there is an issue I still need to get to about fixing a few problems with the appendices, I'll add this to that when I get to it.
