### ISSUE TITLE
Impl -- 6.2, 6.3, and 7.1 seem oddly structured

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#505]
I recommend that the detail in 7.1 instead be placed upwards in 6.2, and that 7.1 be removed entirely, or a brief summary/xref to 6.2. As it stands right now, the structure seems awkward amongst these sections.

**Comment by bracken** [comment]
yeah, I'll see if I can do something. I like that there is a separation between _sending_ events and _receiving_ events and having an explanation for some things in each section isn't that bad since many people will read just one of them and not both.
