### ISSUE TITLE
Impl -- 9.3 Profile Use Cases -- boilerplate TODO code needs replacement/removal

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#508]
We have these TODO remarks in the section 9.3 that need satisfaction, or removal:

> Make sure to get a use case that decides why and how to add custom extensions.
> 
> Need to add use cases for all action types for each profile ( request from issue #196)

**Comment by joshuamcghee** [comment]
@joshuamcghee to add references to use cases as outlined in primary spec doc.

**Comment by joshuamcghee** [comment]
resolved in #529
