### ISSUE TITLE
Impl -- 10 Best Practices and FAQ

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#509]
It feels structurally awkward to combine best practices and FAQ information together. How can you tell whether something is a FAQ or a practice? We should separate these into two different sections.

**Comment by bracken** [comment]
Yeah, I agree it's a bit weird, but half of them work great as both FAQ and best practice like "How much data should be sent in an Event?" and "How are sessions tracked across multiple LTI tools?" so I just shrugged and combined them. :)
I'll separate them and we'll see if that feels better though.

**Comment by bracken** [comment]
actually, I think I'll just name the section best practices only and rename some headers and see how everyone likes that.
