### ISSUE TITLE
Impl -- 10.1 How often is Caliper Updated; should include more detail about extensibility

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#511]
When we say "New Metric Profiles can also be created and published without a new release of Caliper" we should either describe that process in more detail here, or link to a place where that's described. We have a pretty strict and formal way in which we envision doing this, so we should document that process, or not claim that it's possible.

**Comment by bracken** [comment]
I agree, I'll add this as its own commit on top of some of the other changes instead of mixing it with a larger commit because I think we'll have to iterate on this section a bit.

**Comment by bracken** [comment]
@ViktorHaag I think I changed my mind on this. We can still make it more clear, but I think it might be okay to leave it essentially as "we can add profiles and want to, but the process is working with the workgroup to do that", for now. 
It'd be great to eventually make an official process for that and describe it, but I don't think that's something we can get through right now. So, I think it's still valuable to let readers know it's possible in vague "it's the workgroup" terms.

**Comment by joshuamcghee** [comment]
> @ViktorHaag I think I changed my mind on this. We can still make it more clear, but I think it might be okay to leave it essentially as "we can add profiles and want to, but the process is working with the workgroup to do that", for now.
> It'd be great to eventually make an official process for that and describe it, but I don't think that's something we can get through right now. So, I think it's still valuable to let readers know it's possible in vague "it's the workgroup" terms.

I think we can at least give them a direct in road, something like "to begin this process log an issue in the following repo" or "....raise a thread on the caliper project group forum"

**Comment by ViktorHaag** [comment]
Yep, I'm OK with leaving the details within the workings of the working group, but we still should point them to a door as Josh suggests.
