### ISSUE TITLE
Impl --10.3.2 Other LTI Launch information

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#513]
This section says, about `messageParameters`:
```
... but the message bodies are quite large, and you should prefer
to rely in the federated session ID to retrieve any needed information
unless you have a specific purpose for including all that information.
```

We should rephrase this. It's almost certainly likely that the _federatedSession_ will not have a 1:1 unique mapping to LTI launches; rather it will almost certainly have a 1:_n_ mapping to _multiple LTI launches_, each with it's own message parameters.

This makes the presence of `messageParameters` inside the LtiSession object _very problematic indeed_, as the cardinality of the LtiSession may not correspond directly to one set of message parameters.

We should call this discrepancy out here _and_ in the specification. The only really clean way to handle this between LTI Platforms and Caliper events is that _the platform should generate a new 'federated session ID' for each and every LTI launch_, and it's highly unlikely that platforms will do that, I suspect -- instead, they'll probably just pass some "federated session" value that corresponds to the user's _login session on the platform_ (so they don't have to do complicated state management between login sessions and federated sessions passed in LTI launches).

This actually makes the inclusion of "message parameters" quite problematic. 8(

**Comment by joshuamcghee** [comment]
resolved in #533
