### ISSUE TITLE
Impl -- 10.6 JSON-LD should not strongly recommend use of JSON-LD

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#514]
Currently this section says:
> The messages described in this specification are intended to be used in programming environments that support JSON-LD

We should not make this statement so strongly, as  there are significant problems with using JSON-LD operations on Caliper Events without awareness and skill. We should probably moderate this to emphasize that the baseline requirement for Sensors, and receivers, is _not_ that they are JSON-LD capable, but rather that they be able to rely only on simple JSON exactly as specified and presented in the examples (and via the certification test). Caliper-aware components _might_ choose to try to use JSON-LD operations to "understand" or manipulate Caliper documents, but it's absolutely not a requirement at all (and comes with problems that need confronting...)

**Comment by bracken** [comment]
Agreed, how about something like this:

[JSON-LD](https://www.w3.org/2018/jsonld-cg-reports/json-ld/) is a specification providing a JSON-based data serialization and messaging format, processing algorithms and API for working with Linked Data. Implementations of Caliper do not need to utilize JSON-LD itself to emit or consume Caliper events as they can be treated as regular JSON objects. If your implementation utilizes some of the benefits of JSON-LD that is excellent, but it is important to realize most implementations will not.
