### ISSUE TITLE
Impl -- 11.1 CASE integration

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#515]
Note that there exists a challenge in integration with CASE around _identifiers_.

Caliper requires that a `LearningObjective.id` be an IRI; however, the canonical identifier for a CASE item is _not_ an IRI, but is, rather, a UUID string. In fact, the "CASE item URI" is not required to be unique, is somewhat problematic, and is intended not for identification (that's the ID), but rather for dereference to get more properties on an item.

This means that we should _not_ present the learning objectives this way. Rather, we should comment that for use with Caliper, the CASE item _identifier_ (as a UUID) should be presented in Caliper _this way_:
```json
{
   "id": "urn:uuid:2f5e8130-46fa-11e7-b197-cd3432e719f9",
   "type": "LearningObjective",
   "name": "Research techniques",
   "description": "ELAGSE1RL1 Ask and answer questions about key details in a text.",
   "otherIdentifiers": [
         { "type": "SystemIdentifier",
           "identifier": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/2f5e8130-46fa-11e7-b197-cd3432e719f9",
           "identifierType": "Other" }
      ]
}
```

(We should probably include a new System ID vocab item(s) for CASE that are like "CASEItemURL", and etc, for the various CASE item types, but for now without changing Caliper v1.2, we need to use "Other".)

CASE Item URLs are not guaranteed to be canonical at all; only the CASE Item ID is... 8(

**Comment by joshuamcghee** [comment]
added to the agenda for discussion on 2/4/2020 call

**Comment by bracken** [comment]
We will use otherIdentifiers, and we will add a new `identifierType` of `CASEItemURL` (double-check what it's called in CASE)

todo:
- spec updated
- context doc
- ontology
- implementation guide section
- update the fixtures as needed
- file tickets to update sensor library lists for identifierType

**Comment by ViktorHaag** [comment]
We'll want fixture(s) that test this as well; perhaps improving the "Caliper terms in fixtures" PR that Andrew already has in flight (PR #474 ).

**Comment by ViktorHaag** [comment]
> We will use otherIdentifiers, and we will add a new `identifierType` of `CASEItemURL` (double-check what it's called in CASE)

In the CASE 1.0 spec, the `uri` property on the `CFItem` is the property we're looking for here. So, I would say, let's call this the `CaseItemUri` (that mirrors the camel-case naming we've already established with other term values here).

Note that the data type for this property is "AnyURI" and thus, while it's recommended and intended to be a locater, strictly speaking, it doesn't have to be.

(The spec says that an `AnyURI` is an "absolute or relative URI"; I think it's pretty clear that it actually means it should be a _URL_, but it doesn't say that.)

**Comment by bracken** [comment]
I merged Viktor's work, but these still need done:

- Re-upload the context file to IMS purl server because it changed for this
- update ontology
- make sure cert suite has new field as well
