### ISSUE TITLE
Cert 2.2 -- Distinguish between "member" and "representative"

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#518]
AFAIK, generally, IMS uses this terminology:
- A _member_ is the organization that actually holds the membership (i.e. "D2L Corporation").
- A _representative_ is a person that represents a member organization (i.e. "Viktor Haag at D2L Corporation").

We should be sure that the description thus clarifies this:
- Member name --> "D2L Corporation"
- Representative name --> "Viktor Haag"
- Representative email address --> "Viktor.Haag@D2L.com"

**Comment by joshuamcghee** [comment]
@bracken just double checked and the current conformance guide  is how it is laid out in the actual cert suite.  

@ViktorHaag I'm happy to make the change in the guide but will wait til the change is made on the actual cert suite beforehand
