### ISSUE TITLE
Cert 3.x -- Use better visual difference to call out Required elements

### ISSUE THREAD

**Issue by ViktorHaag** [1EdTech/caliper-spec#521]
Because we don't sort the tables to group the required elements together, necessarily, we should consider some way of more clearly calling out the rows that are required.
- We could bold the **Required** word to make it stand out, or italicize it.
- We could include a visual symbol as well, under the "Event" column like `-->` or something.

**Comment by bracken** [comment]
The **Required** word is already bold on each required action row, are you saying we need a way to make it clear the event name that is the parent of that action in the table needs to be marked as required too?

**Comment by joshuamcghee** [comment]
@ViktorHaag I think Bracken's comment was directed to you.

**Comment by ViktorHaag** [comment]
> The **Required** word is already bold on each required action row, are you saying we need a way to make it clear the event name that is the parent of that action in the table needs to be marked as required too?

Hm; maybe it actually is (confirmed: it is; the markup uses `<strong>` around Required, and not around Optional). The visual difference in my browser is so minor as to be almost invisible. 8p

Never mind; not sure if this is a browser thing, or a CSS thing; if it's a CSS thing, then maybe we could beef up the visual difference here a bit.
