### ISSUE TITLE
v1.2 Spec Link Typos

### ISSUE THREAD

**Issue by andrew-gardener** [1EdTech/caliper-spec#546]
**Terminology**
- Context: `IRIs` points to `https://www.ietf.org/rfc/rfc3987.txt` (probably should point to `#iriDef`) https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L468
- Context: `JSON-LD` points to `http://json-ld.org/spec/latest/json-ld/` (probably should point to `#jsonldDef`) https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L92 & https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L94
- JSON-LD: `JSON-LD` points to `http://json-ld.org/spec/latest/json-ld/` (probably should add Normative reference for it and point to that?) https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L129 

**Typos**
- `<a href="actions">` -> `<a href="#actions">` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L253
- `<a href="uuidRef">` -> `<a href="#uuidRef">` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/fragments/events/caliper-event-event.html#L99
- `<a href="http://purl.imsglobal.org/ctx/caliper/v1p2">context</a>document` -> `<a href="http://purl.imsglobal.org/ctx/caliper/v1p2">context</a> document` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/fragments/events/caliper-event-event.html#L107
- `<a href="#audioobject">ImageObject</a>` -> `<a href="#imageobject">ImageObject</a>` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/fragments/profiles/caliper-profile-media.html#L16
- `subsequent attempt.</li><` -> `subsequent attempt.</li>` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/fragments/profiles/caliper-profile-survey.html#L206
- `<a href="endpoint">Endpoint</a>` -> `<a href="#endpoint">Endpoint</a>` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/caliper-spec-v1p2.html#L589
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-feedback.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
	- format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-navigation.html
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-questionnaire.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-questionnaireitem.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-resourcemanagement.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-search.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-survey.html
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-surveyinvitation.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-thread.html
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-toollaunch.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- https://github.com/IMSGlobal/caliper-spec/blob/develop/fragments/events/caliper-event-view.html
    - Remove all `https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html` from links (there are several of them)
    - format of the properties seems a little outdated/inconsistent
- `<a href="metrics">` -> `<a href="#metrics">` https://github.com/IMSGlobal/caliper-spec/blob/ccddf70761052312e5ff9d9ef1fd6b339909c070/fragments/entities/caliper-entity-aggregatemeasure.html#L59

**Comment by bracken** [comment]
I don't know what you meant by "format of the properties seems a little outdated/inconsistent", can you give an example?
I think everything else is fixed in the PR. 

If you do another pass just do a new issue so I don't confuse which ones I've done.

**Comment by andrew-gardener** [comment]
@bracken sorry for being vague about the formatting part. Its mostly that some terms in the description should be updated to links and the wording is slightly different. 

Here are two (`AssignnableEvent` which I believe is the newer format and `FeedbackEvent` which I believe is the outdated format) for side by side comparison:

<img width="385" alt="AssignnableEvent" src="https://user-images.githubusercontent.com/3082802/76784943-cefeec80-6771-11ea-87a6-740930680d1f.png">
<img width="493" alt="FeedbackEvent" src="https://user-images.githubusercontent.com/3082802/76784955-d1614680-6771-11ea-8509-a6b9faf859de.png">

**Comment by andrew-gardener** [comment]
Just to be clear, I don't think the formatting is necessarily wrong, just inconsistent. I'm actually not 100% sure which format is more current either.
